Send signals in parallel
paritytech/orchestra pull request #51
Opened 2023-07-07 14:12 UTC by vstakhov

This PR addresses #18

Rough architecture description.

1) We first try to send signals via `try_send_signal` for each subsystem. This is not an async function and it is blazingly fast for the vast majority of the cases. So it is a fast path.
2) If some subsystem is slow, then we create a new future where we perform the real async `send_signal` function.
3) These futures are joint in `FuturesUnordered` to allow unordered polling. When some subsystem gets ready to accept a signal it immediately receives that signal.

With such an approach, we do not create unnecessary futures nor vectors of futures and we just utilise the fast path via `try_send` in the majority of this function calls.

2023-07-07 14:13 UTC, vstakhov commented
This PR is now based against the master branch to allow CI to do it's job. I will rebase it later.

2023-07-07 16:16 UTC, vstakhov commented
It seems I cannot now change the base branch for this PR :(

2023-07-07 17:29 UTC, vstakhov commented
> It seems I cannot now change the base branch for this PR :(

Ok, Github has fixed this issue I suppose.

2023-07-09 06:54 UTC, drahnr commented on orchestra/proc-macro/src/impl_orchestra.rs
> +					}
```suggestion
					if let Err(e) = self. #subsystem_name .try_send_signal(signal.clone()) {
							match e {
								#support_crate::TrySendError::Full(sig) => {
									let instance = self. #subsystem_name .instance.as_mut().expect("checked in try_send_signal");
									delayed_signals.push(::std::boxed::Box::pin(async move {
										match instance.tx_signal.send(sig).timeout(SIGNAL_TIMEOUT).await {
											None => {
												Err(#error_ty :: from(
													#support_crate ::OrchestraError::SubsystemStalled(instance.name, "signal", ::std::any::type_name::<#signal_ty>())
												))
											}
											Some(res) => {
												let res = res.map_err(|_| #error_ty :: from(
													#support_crate ::OrchestraError::QueueError
												));
												if res.is_ok() {
													instance.signals_received += 1;
												}
												res
											}
										}
									}));
								},
								_ => return Err(#error_ty :: from(#support_crate ::OrchestraError::QueueError))
							}
					}
```

2023-07-09 07:00 UTC, drahnr commented on orchestra/proc-macro/src/impl_orchestra.rs
> +					}
Could be simplified further once `Result::inspect` is stabilized.

2023-07-09 07:01 UTC, drahnr commented on orchestra/proc-macro/src/impl_orchestra.rs
> +						},
```suggestion
					if let Ok(()) = instance.tx_signal.try_send(signal)? {
						instance.signals_received += 1;
						Ok(())
```

2023-07-09 07:02 UTC, drahnr commented on orchestra/proc-macro/src/impl_orchestra.rs
> +		const SIGNAL_TIMEOUT: ::std::time::Duration = ::std::time::Duration::from_secs(10);
nit: needs a doc comment

2023-07-09 07:02 UTC, drahnr requested changes
A few idiomatic suggestions and a missing doc comment, otherwise LGTM

2023-07-10 19:07 UTC, drahnr approved these changes

2023-07-17 10:54 UTC, sandreim approved these changes
Nice! This should likely be more useful outside the context of Polkadot maybe, because a subsystem not handling signals in time is likely stuck because of cycles or other bugs.

2023-07-17 12:44 UTC, merged